CREATE TABLE ACCESOS (
  idACCESOS INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Descripcion VARCHAR(300) NULL,
  Nombre VARCHAR(40) NULL,
  URL VARCHAR(40) NULL,
  Estado CHAR(1) NULL,
  PRIMARY KEY(idACCESOS)
);

CREATE TABLE ADMINISTRADOR (
  idADMINISTRADOR INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idDISTRITO INTEGER UNSIGNED NOT NULL,
  Nombre VARCHAR(30) NULL,
  Ap_Paterno VARCHAR(30) NULL,
  Ap_Materno VARCHAR(30) NULL,
  Usuario VARCHAR(30) NULL,
  clave VARCHAR(30) NULL,
  Nacionalidad VARCHAR(40) NULL,
  Sexo VARCHAR(10) NULL,
  Fc_Nac DATE NULL,
  Estado CHAR(1) NULL,
  Direccion VARCHAR(40) NULL,
  Telefono VARCHAR(20) NULL,
  PRIMARY KEY(idADMINISTRADOR)
);

CREATE TABLE ADMINISTRADOR_has_ACCESOS (
  idADMINISTRADOR INTEGER UNSIGNED NOT NULL,
  idACCESOS INTEGER UNSIGNED NOT NULL,
  Fc_RegistroAccesos DATE NULL,
  PRIMARY KEY(idADMINISTRADOR, idACCESOS)
);

CREATE TABLE ADMINISTRADOR_has_PERFIL (
  idADMINISTRADOR INTEGER UNSIGNED NOT NULL,
  idPERFIL INTEGER UNSIGNED NOT NULL,
  Fc_RegistroPerfil INTEGER UNSIGNED NULL,
  PRIMARY KEY(idADMINISTRADOR, idPERFIL)
);

CREATE TABLE AREA (
  idAREA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idFILIAL INTEGER UNSIGNED NOT NULL,
  Descripcion VARCHAR(40) NULL,
  Nombre VARCHAR(40) NULL,
  PRIMARY KEY(idAREA)
);

CREATE TABLE DISTRITO (
  idDISTRITO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idPROVINCIA INTEGER UNSIGNED NOT NULL,
  Nombre_Distrito VARCHAR(40) NULL,
  Codigo_Postal VARCHAR(40) NULL,
  PRIMARY KEY(idDISTRITO)
);

CREATE TABLE FILIAL (
  idFILIAL INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nombre_Filial VARCHAR(40) NULL,
  PRIMARY KEY(idFILIAL)
);

CREATE TABLE PERFIL (
  idPERFIL INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nombre_Perfil VARCHAR(40) NULL,
  Estado_Perfil CHAR(1) NULL,
  PRIMARY KEY(idPERFIL)
);

CREATE TABLE POSTULANTE (
  idPOSTULANTE INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idDISTRITO INTEGER UNSIGNED NOT NULL,
  Nombre VARCHAR(40) NULL,
  Ap_Paterno VARCHAR(40) NULL,
  Ap_Materno VARCHAR(40) NULL,
  Nacionalidad VARCHAR(40) NULL,
  Sexo CHAR(1) NULL,
  Fec_Nacimiento DATE NULL,
  Telefono VARCHAR(15) NULL,
  usuario VARCHAR(40) NULL,
  clave VARCHAR(40) NULL,
  PRIMARY KEY(idPOSTULANTE)
);

CREATE TABLE POSTULANTE_has_TRABAJO (
  idPOSTULANTE INTEGER UNSIGNED NOT NULL,
  idTRABAJO INTEGER UNSIGNED NOT NULL,
  Fc_envio DATE NULL,
  CV VARCHAR(30) NULL,
  Estado CHAR(1) NULL,
  PRIMARY KEY(idPOSTULANTE, idTRABAJO)
);

CREATE TABLE PROVINCIA (
  idPROVINCIA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idREGION INTEGER UNSIGNED NOT NULL,
  Nombre_Provincia VARCHAR(40) NULL,
  PRIMARY KEY(idPROVINCIA)
);

CREATE TABLE REGION (
  idREGION INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nombre_Region VARCHAR(40) NULL,
  PRIMARY KEY(idREGION)
);

CREATE TABLE SUB_AREA (
  idSUB_AREA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idAREA INTEGER UNSIGNED NOT NULL,
  Descripcion VARCHAR(300) NULL,
  PRIMARY KEY(idSUB_AREA)
);

CREATE TABLE TIPO_TRABAJO (
  idTIPO_TRABAJO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(40) NULL,
  Descripcion VARCHAR(300) NULL,
  PRIMARY KEY(idTIPO_TRABAJO)
);

CREATE TABLE TRABAJO (
  idTRABAJO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idSUB_AREA INTEGER UNSIGNED NOT NULL,
  idTIPO_TRABAJO INTEGER UNSIGNED NOT NULL,
  idFILIAL INTEGER UNSIGNED NOT NULL,
  Nombre VARCHAR(40) NULL,
  Descripcion VARCHAR(300) NULL,
  Vacantes INTEGER UNSIGNED NULL,
  Fc_InicioPublicacion DATE NULL,
  Fc_FinPublicacion DATE NULL,
  Estado CHAR(1) NULL,
  PRIMARY KEY(idTRABAJO)
);


